# Generated by Django 3.1.4 on 2020-12-30 06:27

import backend.apps.horeca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horeca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horeca',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=backend.apps.horeca.models.Horeca.qr_to),
        ),
    ]
