# Generated by Django 3.1.4 on 2020-12-30 06:29

import backend.apps.horeca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horeca', '0002_auto_20201230_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horeca',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=backend.apps.horeca.models.Horeca.upload_to),
        ),
        migrations.AlterField(
            model_name='horeca',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to=backend.apps.horeca.models.Horeca.qr_to),
        ),
    ]
